#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc config focused_border_color \#8ec07c

bspc config border_width 	              1
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle              true
bspc config pointer_follows_monitor     true
bspc config focus_follows_pointer       true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config split_ratio                 0.52
bspc config top_padding                 20

workspaces_multimonitor &

bspc rule -a firefoxdeveloperedition desktop='1' follow=on 
bspc rule -a Brave-browser desktop='1' follow=on 
bspc rule -a code-oss desktop='2' follow=on
bspc rule -a Code desktop='2' follow=on
bspc rule -a Thunar desktop='4' follow=on
bspc rule -a vlc desktop='7' follow=on
bspc rule -a discord desktop='8'
bspc rule -a obs desktop='0' follow=on
bspc rule -a ViberPC desktop='0' 

bspc config external_rules_command "$HOME/.config/bspwm/scripts/custom-rules"

$HOME/.config/polybar/launch.sh &
picom --config $HOME/.config/picom/picom.conf &
nm-applet &
copyq &
nitrogen --restore &

$HOME/.screenlayout/setScreen.sh
$HOME/.config/bspwm/scripts/monitor.sh
