#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc confis window_gap		13
bspc config focus_follows_pointer false

bspc config pointer_follows_monitor true
#bspc config pointer_follows_focus true

bspc config border_width 	1
bspc config top_padding 25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

workspaces_multimonitor &

bspc rule -a firefoxdeveloperedition desktop='I' follow=on 
bspc rule -a code-oss desktop='II' follow=on
bspc rule -a Thunar desktop='IV' follow=on
bspc rule -a vlc desktop='VII' follow=on
bspc rule -a discord desktop='VIII'
bspc rule -a obs desktop='X' follow=on
bspc rule -a ViberPC desktop='X' 

bspc config external_rules_command "$HOME/.config/bspwm/scripts/custom-rules"

$HOME/.config/polybar/launch.sh &
picom --experimental-backends --config $HOME/.config/picom/picom.conf &
nm-applet &
copyq &
nitrogen --restore &

$HOME/.config/bspwm/scripts/monitor.sh
