#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap		13
bspc config focus_follows_pointer false
bspc config border_width 	1
bspc config top_padding 25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Chromium desktop='^1'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh &
picom --experimental-backends --config $HOME/.config/picom/picom.conf &
nm-applet &
copyq &
nitrogen --restore &
redshift -P &
